descriptor-schema-version: "2.3"

info:
  name: "Cisco IOx KVM Alpine Docker Application"
  description: "KVM Alpine Docker Daemon Application"
  version: "1.0"
  author-link: "http://www.cisco.com"
  author-name: "Cisco Systems"

app:
  # Indicate app type (vm, lxc, docker)
  type: vm
  cpuarch: "x86_64"
  resources:
    profile: custom
    cpu: 7000
    memory: 1024
    disk: 5
    vcpu: 2

    network:
      -
        interface-name: eth0

# Specify runtime and startup
  startup:
    disks:
       -
        target-dev: "hdc"
        file: "alpine37-docker.v1.0.qcow2"

    qemu-guest-agent: True

